### PR TITLE
docs: fix add minimal docker example

### PR DESCRIPTION
**Pull request by srenatus**
Just a small addition to blaze a tiny trail for the next person 😉

### CODE REVIEW

**Comment by jemc** [comment]
Thanks for helping out!

However, the intention here for this page was to run the `jemc/jylis` docker image, which is built from the `master` by dockerhub. That's a little easier than using `busybox` and mounting the binary into it as you've done here.

Would you mind revising the example to use the `jemc/jylis` image?

**Comment by srenatus** [comment]
Sure. :) won't be on a computer before Wednesday, though.

**Comment by srenatus** [comment]
ℹ️ This is probably some local issue; I just realised it's happening with the other method (volume-mounting the executable) for me, now, too. Must have upgraded docker or screwed up something else in my environment.

**Comment by srenatus** [comment]
Got a good idea how it used to look when it was still working for me -- so I've updated the PR with that.

**Comment by jemc** [comment]
I've actually just merged another PR for this content (#4), because the image was working for this person, and they've included a few more examples of use (with `docker-compose`, etc).

I've opened #6 to investigate the portability issues we were discussing here.

Sorry for the inconvenience.

**Comment by srenatus** [comment]
@jemc sure, no worries 👍

**Pull request closed without merging**
